### PR TITLE
FEAT: adds terminal growl notifier to cljsbuild dev ☕️

### PR DESCRIPTION
**Pull request by dviramontes**
~~Requires [`terminal-notifier`](https://github.com/julienXX/terminal-notifier)
You can install with `brew install terminal-notifier`~~

After that you can run the `./script/figwheel-repl.sh` as per usual, then go grab ☕️ 
The notifier will notify you when your build is complete (or if it failed to build).

Looks like: 
feb-21-2017 20-42-42

#### TODO: 

- [ ] fix run notify script 
- [ ] add instructions to README

### CODE REVIEW

**Review by tylerperkins — CHANGES_REQUESTED** [review]
Cool idea, David, but I have a couple problems with it. :-/

First, if you don't install terminal-notifier and, by the way, iTerm2, you get a big, ugly exception on startup. This will happen whenever someone (like me) has no desire to install these, or just can't because they're not on a Mac. Although the `README.md` instructions only cover MacOS, there is nothing _in the code_ that favors any particular (POSIX-compliant) OS.

So how about these suggestions:

1. Introduce a level of abstration in order to allow for customization:
   - Check in an executable Bash script, `script/notify_command.sh` that does nothing but execute file `~/.owlet_repl_ready`, if present. The key point here is that the user can supply `~/.owlet_repl_ready` to do at app startup whatever he/she wants, _and_ it is not checked in. For example, they could just write a one-line script, `terminal-notifier -title ...`.
   - In `project.cljs`, replace `:notify-command ["terminal-notifier" ...`,
     with `:notify-command ["script/notify_command.sh"]

2. Instructions for how to install terminal-notifier and write `~/.owlet_repl_ready` should be in a separate section, say `#### Get Notified` just before the section `## Run tests`. The section `- You'll also need the command-line utilities ...` is strictly for what is required -- nothing optional.

**Comment by dviramontes** [comment]
@tylerperkins yes! thats a great idea. An opt-in teminal_notifier config sounds great!
Another thing that i did not consider is that travis has no way of running this notifier so notifier will  throw and our build will break 😆

**Comment by dviramontes** [comment]
@tylerperkins so potentially this plank shell script has the same problem with not being universal but I decided it would be a cool experiment to try to write in clojure (because awesome) since [plank now runs on other linux distros](https://github.com/mfikes/planck#installing). Anyways more to come on that.. 
I still need to figure out why its throwing this one error: `launch path not accessible` ¯\_(ツ)_/¯

**Comment by tylerperkins** [comment]
Very cool experiment, to be sure. You might actually convince me if you could do it in CLJ & Clojure instead of CLJS & Planck -- no additional dependencies required! I think it's possible with a bit of Leiningen wizardry. (It's probably a no-brainer in Boot!)

Come to think of it, if you did that, I'd rewrite my two `script/*.sh`files in CLJ and we wouldn't even need Bash! Might even make life easier for Windoze users.

But dude, seriously? We already require Bash, so how 'bout this:

    #!/usr/bin/env bash

    READY_SCRIPT=~/owlet_repo_ready
    if test -f $READY_SCRIPT; then
        $READY_SCRIPT
    fi

**Comment by tylerperkins** [comment]
An even better solution just hit me! In Leiningen there is [`:init`, an option for `:repl-options`](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L365). Just put CLJ code there to do the checking for and running ~/.owlet_repl_ready.

**Review by ZadenRB — APPROVED** [review]
👍  Looks good!

**Pull request merged**
