### PR TITLE
refactor: events ns

### LINKED ISSUE #198: events refactor
refactor events `:close-sidebar!`, `:navigate-to-view!`, and URI decoder (in the routes) to use a reg-fx function, not a reg-cofx function

from @tylerperkins:

>I'm concerned that effects are creeping into coeffects, especially when they manipulate the DOM. This applies to :close-sidebar! as well as :navigate-to-view!.

>First, coeffects are for making data from the outside world available to handlers. That's it. Effects are for handlers to send data to the outside world, such as a database or, regrettably, even the browser.

>Second, it's React's job to manage the DOM, so in my understanding, direct DOM manipulation should be avoided. As you know, components should be written with reactions, i.e. (subscribe ...), so they define dynamic properties of the created DOM elements.

>This purity may seem difficult when we're interfacing with JS code that manipulates the DOM, but maybe we should try. For example, if you really have to touch the DOM, at least do it in a reg-fx function, not in a reg-cofx function. Staying as true as we can to the spirit of re-frame will save headaches down the line, I think.

### PR DESCRIPTION
**Pull request by dviramontes**
closes https://github.com/codefordenver/owlet/issues/198

new event categories are:
- contentful
- firebase 
- app

### CODE REVIEW

**Comment by tylerperkins** [comment]
Thanks for doing this, @dviramontes! I do have a couple of requests:

- The "firebase" namespace should really be called "auth", since it's only concerned with authentication and authorization, and it involves events from Auth0 as well as Firebase.

- Regarding the name "helpers": I think of a _helper function_ as being special-purpose, usually residing near the function that needs it. Maybe `reg-setter` really belongs with `reg-getter` (now in `subs`) in, say, `owlet-ui.rf-util`, one level up. The idea is that this namespace essentially extends the re-frame framework for use in any application.

- Function `note-pending` is really closer to being a helper function special-purposed to our app, and probably belongs in `app` (and should no longer be private). It can (and should) be used to provide feedback to the user when any operation takes a while.

If you like, I can make these changes myself. What do you think?

**Comment by dviramontes** [comment]
Ok cool, yeah I like `auth` instead of `firebase` too. Yeah go ahead and push
those changes. I'll take a look later today. Thanks @tylerperkins !

**Comment by tylerperkins** [comment]
@dviramontes 

Wow, that was tough! There were things to fix that had slipped through, probably because you didn't restart the app. Unless you do, definitions in old namespaces hang around, masking outdated requires, etc. The hardest part, however, was merging Michelle's recent changes, since so many were in events.cljs, which is now gone. Using Git diff-ing doesn't help, since it just shows you the difference between the entirety of events.cljs with ... nothing!

So, thorough testing is in order. Especially since I also heavily refactored event handler `:get-library-content-from-contentful-successful`. (It started in the merge ordeal just fixing some indentation, then I couldn't stop!) Anyway, I think it's comprehensible now.

Let me know if this looks good, and I'll go ahead and "squash and merge".

**Comment by tylerperkins** [comment]
Oh, and @eemshi, please also take a look to see if I merged your new changes properly.

**Review by eemshi — APPROVED** [review]

**Pull request merged**
