### PR TITLE
Adds cuerdas dependency, fixes skill display name capitalization

### LINKED ISSUE #248: Some skills improperly capitalized when searched

### PR DESCRIPTION
**Pull request by ZadenRB**
closes https://github.com/codefordenver/owlet/issues/248

### CODE REVIEW

**Review by dviramontes — APPROVED** [review]
code lgtm, i think @eemshi wanted to functionally test it as well

**Comment by eemshi** [comment]
sorry for the delay - let's merge this!

**Review by eemshi — APPROVED** [review]

**Comment by eemshi** [comment]
Hey @ZadenRB @dviramontes do you get this console error when you try to go to another skill (CSS) via search from a skill page (HTML)?

screen shot 2017-08-10 at 8 38 14 pm

This looks like the same error you solved by wrapping something in a `(fn [])`

**Comment by dviramontes** [comment]
thanks @eemshi, lets hold on merging this for now.

**Comment by dviramontes** [comment]
@ZadenRB can you take a look ?^

**Comment by dviramontes** [comment]
@ZadenRB @eemshi looks like we just needed to `lower-case` the term when doing the `indexOf` look up. Should be fixed now. Let me know. Thanks!

**Pull request merged**
