### PR TITLE
refactors activity event + view to handle loading / nonexistent cases

### PR DESCRIPTION
**Pull request by eemshi**
Began looking at how we might have more nuanced display messages to differentiate between "loading" and "does not exist." If this looks good to yall we can use a similar method for branch-view, search results, etc. Other ideas welcome!

### CODE REVIEW

**Review by ZadenRB — CHANGES_REQUESTED** [review]
When navigating from an existing branch to a non-existent activity, the message remains as "loading..." until refresh, and when navigating from a non-existent activity to an existing branch, the "This branch does not exist" message is displayed until refresh.

**Review by dviramontes — APPROVED** [review]
@ZadenRB I don't see the behavior you are describing in your comment (make sure you have the latest state of this branch, the commit hash should be `eb931bb2014a5cf2e0b15e370074ea18b27acd26`).

I pull it down and tested it locally and it looks good. In fact navigating from branch -> activity appears more smooth. 👏 

I did discover an error in the process of testing this having to do with the `[search-bar]`  component though but I'll log it separately. This looks good to me 👍

**Comment by ZadenRB** [comment]
@dviramontes I only see it when navigating via browser navigation buttons, not on-site navigation.

**Comment by eemshi** [comment]
Ok thanks, cant look into it tonight but should be able to tomorrow

**Comment by eemshi** [comment]
@ZadenRB @dviramontes for now i just added the back arrow component. since the browser navigation is a larger issue with the routes i'll put it on a separate card

**Pull request merged**
